### ISSUE TITLE
How to send message to Viber Bot?

### ISSUE THREAD

**Issue by dkultasev** [MaxOvcharov/ViberBot#1]
Hi Max,
could you please help me by providing simple example how to send message to Viber bot? I've started HTTPS server something like you have in your code, but how to send the message then?

Thanks in advance.

**Comment by msovcharov** [comment]
Hi, did you configure your Viber App and public account - https://developers.viber.com/docs/general/get-started/?

**Comment by dkultasev** [comment]
yes. And I have the token already

**Comment by msovcharov** [comment]
Here it is [entry point](https://github.com/MaxOvcharov/ViberBot/blob/0a6f947edccd9e5ecb27ec4aac5a516fbb68d7b5/ViberBot/simpleViberBot/simpleViberBot.py#L36) for yours messages from Viber.
